version: '3.7'
services:
    server:
        build: .
        command:
            bash -c 'flask run --debugger --reload --host=0.0.0.0 --port=5000'
        ports:
            - "5000:5000"
        volumes:
            -   .:/code
